INSERT INTO smn_banco.smn_movimiento_bancario
(	smn_movimiento_bancario_id,
	smn_entidades_rf,
	smn_sucursal_rf,
	smn_entidad_financiera_id,
	smn_cuenta_bancaria_rf,
	mov_numero_documento,
	smn_documento_id,
	smn_tipo_documento_id,
	mov_descripcion_movimiento,
	mov_beneficiario_pago,
	mov_tipo_movimiento,
	mov_monto_ml,
	smn_moneda_rf,
	mov_fecha_documento,
	smn_tasa_rf,
	mov_estatus_proceso,
	mov_estatus,
	mov_idioma,
	mov_usuario,
	mov_fecha_registro,
	mov_hora
)
VALUES
(	${seq:nextval@smn_banco.seq_smn_movimiento_bancario},
	${fld:smn_entidades_rf},
	${fld:smn_sucursal_rf},
	${fld:smn_entidad_financiera_id},
	${fld:smn_cuenta_bancaria_rf},
	${fld:mov_numero_documento},
	${fld:smn_documento_id},
	(select smn_tipo_documento_id from smn_banco.smn_documento where smn_documento_id=${fld:smn_documento_id}),
	${fld:mov_descripcion_movimiento},
	${fld:mov_beneficiario_pago},
	${fld:mov_tipo_movimiento},
	${fld:mov_monto_ml},
	${fld:smn_moneda_rf},
	${fld:mov_fecha_documento},
	${fld:smn_tasa_rf},
	'RE',
	'RE',
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}')