INSERT INTO smn_banco.smn_equivalencia_doc_bancario
(
	smn_equivalencia_doc_bancario_id,
	smn_documento_id,
	smn_entidad_financiera_id,
	edb_doc_equiv_bancario,
	smn_tipo_documento_id,
	edb_descrip_bancaria,
	edb_estatus,
	edb_vigencia,
	edb_idioma,
	edb_usuario,
	edb_fecha_registro,
	edb_hora
)
VALUES
(
	${seq:currval@smn_banco.seq_smn_equivalencia_doc_bancario},
	${fld:smn_documento_id},
	${fld:smn_entidad_financiera_id},
	${fld:edb_doc_equiv_bancario},
	${fld:smn_tipo_documento_id},
	${fld:edb_descrip_bancaria},
	${fld:edb_estatus},
	${fld:edb_vigencia},
	'${def:locale}',
	'${def:user}',
	{d '${def:date}'},
	'${def:time}'
)
