insert into smn_banco.smn_movimiento_bancario(
smn_movimiento_bancario_id,
  smn_entidades_rf,
  smn_sucursal_rf,
  smn_entidad_financiera_id,
  smn_cuenta_bancaria_rf,
  smn_documentos_generales_rf,
  mov_numero_documento,
  smn_modulo_origen_rf,
  smn_documento_id,
  mov_numero_documento_modulo,
  smn_tipo_documento_id,
  smn_equivalencia_doc_bancario_id,
  mov_descripcion_movimiento,
  mov_beneficiario_pago,
  mov_tipo_movimiento,
  mov_monto_ml,
  smn_moneda_rf,
  mov_fecha_documento,
  smn_tasa_rf,
  mov_monto_ma,
  mov_fecha_entrega,
  mov_fecha_disponible,
  mov_estatus_proceso,
  mov_estatus,
  mov_idioma,
  mov_usuario,
  mov_fecha_registro,
  mov_hora
)
VALUES(
nextval('smn_banco.seq_smn_movimiento_bancario'),
${fld:entidad_rf},
${fld:sucursal_rf},
${fld:banco_rf},
${fld:cuenta_bancaria_rf},
(Select smn_documento_general_rf from smn_banco.smn_equivalencia_doc_bancario inner join smn_banco.smn_documento on smn_banco.smn_documento.smn_documento_id=smn_banco.smn_equivalencia_doc_bancario.smn_documento_id where smn_equivalencia_doc_bancario_id=${fld:equivalencia_ban}),
${fld:numero_ref_bancaria}, -- mov_numero_documento,
(Select smn_modulos_id from smn_base.smn_modulos where mod_codigo='SMN_BAN'),
(Select smn_documento_id from smn_banco.smn_equivalencia_doc_bancario where smn_equivalencia_doc_bancario_id=${fld:equivalencia_ban}),
0, -- mov_numero_documento_modulo,
${fld:tipo_doc_id},
${fld:equivalencia_ban},
${fld:descripcion},
'', -- mov_beneficiario_pago
(Select smn_banco.smn_documento.doc_tipo_movimiento from smn_banco.smn_equivalencia_doc_bancario inner join smn_banco.smn_documento on smn_banco.smn_documento.smn_documento_id=smn_banco.smn_equivalencia_doc_bancario.smn_documento_id where smn_equivalencia_doc_bancario_id=${fld:equivalencia_ban}),
${fld:monto_ml_ban},  --mov_monto_ml,
${fld:moneda_rf},  --smn_moneda_rf,
${fld:fecha},  -- mov_fecha_documento,
${fld:tasa_rf},  --smn_tasa_rf,
${fld:monto_ma_ban},  --mov_monto_ma,
${fld:fecha},  --mov_fecha_entrega,
${fld:fecha},  --mov_fecha_disponible,
'CN',  --mov_estatus_proceso,
'GE', -- mov_estatus,
'${def:locale}',
'${def:user}',
{d '${def:date}'},
'${def:time}'
)
RETURNING smn_movimiento_bancario_id as mov_id
